package com.arthencity.example

// ... existing code ...
class MainActivity : ReactActivity() {
  // ... existing code ...
  override fun getMainComponentName(): String = "ArthencityExample"
  // ... existing code ...
}